minimum-post: 1000.0
maximum-post: 1000000000.0
expire-days: 30
refund-expired: true
history-limit: 5000
milestones:
  high-value-claim: 100000.0
broadcast:
  post-threshold: 100000.0
  claim-threshold: 100000.0
messages:
  prefix: "&5&lMira &8>> &r"
